add contributing and readme redirect to it
TheRealHoko/config-editor pull request #10
Opened 2024-04-23 20:04 UTC by TheRealHoko

2024-04-23 20:07 UTC, STR4Z requested changes

2024-04-23 20:07 UTC, STR4Z commented on CONTRIBUTING.md
> +<!-- TODO: build for react -->
You should do the build for React before we merge that in my opinion

2024-04-25 21:22 UTC, Born-yz approved these changes
Good for me.

2024-04-25 21:26 UTC, STR4Z approved these changes
Hi, the both files seems to be compliant i approve.

2024-04-25 21:27 UTC, merged